### ISSUE TITLE
"The bot withdraw function is a function that the only 'the bot' can call."

### ISSUE THREAD

**Issue by whatisgravity** [BitySA/whetcwithdraw#1]
Is this a joke?

Did you not learn from 'The DAO" contract to not add needless complexity because it can have unforeseen consequences? 

This contract should be made as simple as possible. Being reckless with security to cater to convenience is what lead this entire problem.

"The bot" key is essentially like giving yourself an administrator key over the contract, it is a poorly written back door. If that key is compromised the entire amount could be stolen. From what I have seen so far I do not think it wise to trust you with the responsibility of protecting that key. The escape hatch introduces some similar trust issues.

**Comment by BitySA** [comment]
Thank you for your comment.

It is not a backdoor, but simply a means of allowing other people to give us a directive to perform withdrawals for them.

We are still considering whether or not to offer this functionality. Including your issue report, we have gotten various mixed feedback about it from the community. It may be removed. We take all feedback on the contract very seriously.

Thank you for taking the time to review the withdrawal contract.

**Comment by whatisgravity** [comment]
Even if you don't call something a back door, it still functions as one if someone obtains that key pair, so it is one. That is how most back doors operate. 

And your failure to remove complexity has led to a new bug and you were explicitly warned not to add any unnecessary complexity.
